export const GET_STUDY_PROCESS = 'GET_STUDY_PROCESS_ID';
export const GET_STUDY_PROCESS_SUCCESS = 'GET_STUDY_PROCESS';
export const GET_STUDY_PROCESS_DENIED = 'GET_STUDY_DENIED';
export const CLEAR_STUDY_PROCESS = 'CLEAR_STUDY_PROCESS';
